// Auto-generated by scripts/sync-contract-address.js
// Do not edit manually.

export const CHAIN_ID = 31337 as const;

export const CONTRACT_ADDRESSES = {
  dscEngine: "0x3aa5ebb10dc797cac828524e59a333d0a371443c",
  decentralizedStableCoin: "0x68b1d87f95878fe05b998f19b66f4baba5de1aed",
  weth: "0x0b306bf915c4d645ff596e518faf3f9669b97016",
  wbtc: "0x9a9f2ccfde556a7e9ff0848998aa4a0cfd8863ae",
  ethUsdPriceFeed: "0x9a676e781a523b5d0c0e43731313a708cb607508",
  btcUsdPriceFeed: "0x959922be3caee4b8cd9a407cc3ac1c251c2007b1",
} as const;

export const DSC_ENGINE_ADDRESS = CONTRACT_ADDRESSES.dscEngine;
export const DECENTRALIZED_STABLE_COIN_ADDRESS =
  CONTRACT_ADDRESSES.decentralizedStableCoin;

export const WETH_ADDRESS = CONTRACT_ADDRESSES.weth;
export const WBTC_ADDRESS = CONTRACT_ADDRESSES.wbtc;

export const ETH_USD_PRICE_FEED_ADDRESS =
  CONTRACT_ADDRESSES.ethUsdPriceFeed;
export const BTC_USD_PRICE_FEED_ADDRESS =
  CONTRACT_ADDRESSES.btcUsdPriceFeed;
