// Auto-generated by scripts/sync-contract-address.js
// Do not edit manually.

export const CHAIN_ID = 31337 as const;

export const CONTRACT_ADDRESSES = {
  dscEngine: "0x7a2088a1bfc9d81c55368ae168c2c02570cb814f",
  decentralizedStableCoin: "0x4a679253410272dd5232b3ff7cf5dbb88f295319",
  weth: "0x4ed7c70f96b99c776995fb64377f0d4ab3b0e1c1",
  wbtc: "0xa85233c63b9ee964add6f2cffe00fd84eb32338f",
  ethUsdPriceFeed: "0x59b670e9fa9d0a427751af201d676719a970857b",
  btcUsdPriceFeed: "0x322813fd9a801c5507c9de605d63cea4f2ce6c44",
} as const;

export const DSC_ENGINE_ADDRESS = CONTRACT_ADDRESSES.dscEngine;
export const DECENTRALIZED_STABLE_COIN_ADDRESS =
  CONTRACT_ADDRESSES.decentralizedStableCoin;

export const WETH_ADDRESS = CONTRACT_ADDRESSES.weth;
export const WBTC_ADDRESS = CONTRACT_ADDRESSES.wbtc;

export const ETH_USD_PRICE_FEED_ADDRESS =
  CONTRACT_ADDRESSES.ethUsdPriceFeed;
export const BTC_USD_PRICE_FEED_ADDRESS =
  CONTRACT_ADDRESSES.btcUsdPriceFeed;
