// Auto-generated by scripts/sync-contract-address.js
// Do not edit manually.

export const CHAIN_ID = 31337 as const;

export const CONTRACT_ADDRESSES = {
  dscEngine: "0xe6e340d132b5f46d1e472debcd681b2abc16e57e",
  decentralizedStableCoin: "0x67d269191c92caf3cd7723f116c85e6e9bf55933",
  weth: "0x7a2088a1bfc9d81c55368ae168c2c02570cb814f",
  wbtc: "0xc5a5c42992decbae36851359345fe25997f5c42d",
  ethUsdPriceFeed: "0x4a679253410272dd5232b3ff7cf5dbb88f295319",
  btcUsdPriceFeed: "0x09635f643e140090a9a8dcd712ed6285858cebef",
} as const;

export const DSC_ENGINE_ADDRESS = CONTRACT_ADDRESSES.dscEngine;
export const DECENTRALIZED_STABLE_COIN_ADDRESS =
  CONTRACT_ADDRESSES.decentralizedStableCoin;

export const WETH_ADDRESS = CONTRACT_ADDRESSES.weth;
export const WBTC_ADDRESS = CONTRACT_ADDRESSES.wbtc;

export const ETH_USD_PRICE_FEED_ADDRESS =
  CONTRACT_ADDRESSES.ethUsdPriceFeed;
export const BTC_USD_PRICE_FEED_ADDRESS =
  CONTRACT_ADDRESSES.btcUsdPriceFeed;
